import Head from 'next/head';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { MainLayout } from '@/components/layout';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ul>
          <li>
            <Link href="/about">Go to about page</Link>
          </li>
          <li>
            <Link
              href={{
                pathname: '/categories/[category]',
                query: { category: 123, categories: 'xyz' },
              }}
              legacyBehavior
            >
              <a style={{ color: '#fcb103' }}>Go to category page</a>
            </Link>
          </li>
          <li>
            <Link href="/posts">Go to posts page</Link>
          </li>
        </ul>
      </div>
    </div>
  );
}

Home.Layout = MainLayout;
